# Server Configuration
server.port=8081

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://aanvi24bcs10170_db_user:xPU154PHqK2PzcxZ@cluster0.mu61ks5.mongodb.net/?appName=Cluster0

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationPleaseChangeThisInProduction
jwt.expiration=86400000

# Logging
logging.level.com.aanvi.rideshare=DEBUG